import { describe, expect, it } from "vitest";
import { MockRandomProvider, SeededRandomProvider } from "@game-store/game-core";
import { UnoEngine, createUnoDeck, isUnoCardPlayable, replayUno, type UnoAction, type UnoGameState } from "../engine";

const config = { players: [{ id: "p1", name: "Alice" }, { id: "p2", name: "Bot", kind: "BOT" as const }] };
function game(): { engine: UnoEngine; state: UnoGameState } { const engine = new UnoEngine(new SeededRandomProvider(42)); return { engine, state: engine.createInitialState(config) }; }
function state(overrides: Partial<UnoGameState> = {}): UnoGameState {
  const { state: base } = game();
  return { ...base, players: [{ ...base.players[0]!, hand: [{ id: "red-5", color: "RED", type: "NUMBER", number: 5 }] }, { ...base.players[1]!, hand: [{ id: "blue-5", color: "BLUE", type: "NUMBER", number: 5 }] }], discardPile: [{ id: "red-2", color: "RED", type: "NUMBER", number: 2 }], drawPile: [{ id: "green-1", color: "GREEN", type: "NUMBER", number: 1 }], currentColor: "RED", ...overrides };
}

describe("UNO deck and setup", () => {
  it("creates the standard 108 unique cards", () => { const deck = createUnoDeck(); expect(deck).toHaveLength(108); expect(new Set(deck.map((card) => card.id)).size).toBe(108); });
  it("deals seven cards and starts on a number card", () => { const { state } = game(); expect(state.players.every((player) => player.hand).valueOf()).toBe(true); expect(state.players[0]!.hand).toHaveLength(7); expect(state.discardPile[0]!.type).toBe("NUMBER"); });
});

describe("UNO actions", () => {
  it("accepts color and value matches and rejects unrelated cards", () => { const current = state(); expect(isUnoCardPlayable({ id: "blue-5", color: "BLUE", type: "NUMBER", number: 5 }, current)).toBe(false); expect(isUnoCardPlayable({ id: "red-3", color: "RED", type: "NUMBER", number: 3 }, current)).toBe(true); expect(isUnoCardPlayable({ id: "blue-2", color: "BLUE", type: "NUMBER", number: 2 }, current)).toBe(true); });
  it("requires a color for wild cards", () => { const current = state({ players: [{ ...state().players[0]!, hand: [{ id: "wild", color: "WILD", type: "WILD" }] }, state().players[1]!] }); const engine = new UnoEngine(new SeededRandomProvider(1)); expect(engine.validateAction(current, { type: "PLAY_CARD", playerId: "p1", cardId: "wild" })).toMatchObject({ valid: false, code: "COLOR_REQUIRED" }); });
  it("draws once and requires passing before changing turn", () => { const { engine } = game(); const current = state(); const drawn = engine.reduce(current, { type: "DRAW_CARD", playerId: "p1" }); expect(drawn.state.players[0]!.hand).toHaveLength(2); expect(engine.validateAction(drawn.state, { type: "DRAW_CARD", playerId: "p1" })).toMatchObject({ valid: false, code: "ALREADY_DREW" }); const passed = engine.reduce(drawn.state, { type: "PASS_TURN", playerId: "p1" }); expect(passed.state.currentPlayerIndex).toBe(1); });
  it("applies skip, reverse, and draw-two effects", () => { const engine = new UnoEngine(new SeededRandomProvider(2)); const spare = { id: "spare", color: "BLUE" as const, type: "NUMBER" as const, number: 8 }; const skip = state({ players: [{ ...state().players[0]!, hand: [{ id: "skip", color: "RED", type: "SKIP" }, spare] }, state().players[1]!] }); expect(engine.reduce(skip, { type: "PLAY_CARD", playerId: "p1", cardId: "skip" }).state.currentPlayerIndex).toBe(0); const reverse = state({ players: [{ ...state().players[0]!, hand: [{ id: "reverse", color: "RED", type: "REVERSE" }, spare] }, state().players[1]!], direction: 1 }); expect(engine.reduce(reverse, { type: "PLAY_CARD", playerId: "p1", cardId: "reverse" }).state.direction).toBe(-1); const draw = state({ players: [{ ...state().players[0]!, hand: [{ id: "draw2", color: "RED", type: "DRAW_TWO" }, spare] }, state().players[1]!] }); const result = engine.reduce(draw, { type: "PLAY_CARD", playerId: "p1", cardId: "draw2" }); expect(result.state.players[1]!.hand).toHaveLength(3); expect(result.state.currentPlayerIndex).toBe(0); });
  it("selects a wild color and applies wild-draw-four", () => { const engine = new UnoEngine(new SeededRandomProvider(3)); const wild = state({ players: [{ ...state().players[0]!, hand: [{ id: "wild", color: "WILD", type: "WILD" }, { id: "spare", color: "BLUE", type: "NUMBER", number: 8 }] }, state().players[1]!] }); expect(engine.reduce(wild, { type: "PLAY_CARD", playerId: "p1", cardId: "wild", chosenColor: "YELLOW" }).state.currentColor).toBe("YELLOW"); const drawFour = state({ players: [{ ...state().players[0]!, hand: [{ id: "wild4", color: "WILD", type: "WILD_DRAW_FOUR" }, { id: "spare", color: "BLUE", type: "NUMBER", number: 8 }] }, state().players[1]!], drawPile: [{ id: "a", color: "RED", type: "NUMBER", number: 1 }, { id: "b", color: "RED", type: "NUMBER", number: 2 }, { id: "c", color: "RED", type: "NUMBER", number: 3 }, { id: "d", color: "RED", type: "NUMBER", number: 4 }] }); const result = engine.reduce(drawFour, { type: "PLAY_CARD", playerId: "p1", cardId: "wild4", chosenColor: "GREEN" }); expect(result.state.players[1]!.hand).toHaveLength(5); expect(result.events.some((event) => event.type === "PENALTY_DRAWN" && event.amount === 4)).toBe(true); });
  it("reshuffles discard cards when the draw pile is empty", () => { const { engine } = game(); const current = state({ drawPile: [], discardPile: [{ id: "top", color: "RED", type: "NUMBER", number: 2 }, { id: "old", color: "BLUE", type: "NUMBER", number: 7 }], currentColor: "RED" }); const result = engine.reduce(current, { type: "DRAW_CARD", playerId: "p1" }); expect(result.state.players[0]!.hand).toHaveLength(2); expect(result.state.discardPile).toHaveLength(1); expect(result.state.discardPile[0]!.id).toBe("old"); });
  it("finishes when the final card is played", () => { const { engine } = game(); const current = state({ players: [{ ...state().players[0]!, hand: [{ id: "red-2", color: "RED", type: "NUMBER", number: 2 }] }, state().players[1]!] }); const result = engine.reduce(current, { type: "PLAY_CARD", playerId: "p1", cardId: "red-2" }); expect(result.state.phase).toBe("FINISHED"); expect(engine.checkGameOver(result.state)).toMatchObject({ outcome: "WIN", winnerId: "p1" }); });
});

describe("UNO replay and safety", () => {
  it("rejects invalid turns and cards", () => { const { engine } = game(); const current = state({ players: [{ ...state().players[0]!, hand: [{ id: "red-5", color: "RED", type: "NUMBER", number: 5 }, { id: "blue-5", color: "BLUE", type: "NUMBER", number: 5 }] }, state().players[1]!] }); expect(engine.validateAction(current, { type: "PLAY_CARD", playerId: "p2", cardId: "blue-5" })).toMatchObject({ valid: false, code: "NOT_YOUR_TURN" }); expect(engine.validateAction(current, { type: "PLAY_CARD", playerId: "p1", cardId: "blue-5" })).toMatchObject({ valid: false, code: "CARD_NOT_PLAYABLE" }); });
  it("serializes and replays to the same final state", () => { const { engine } = game(); let current = state(); const actions: UnoAction[] = [{ type: "DRAW_CARD", playerId: "p1" }, { type: "PASS_TURN", playerId: "p1" }]; for (const action of actions) current = engine.reduce(current, action).state; const restored = engine.deserialize(engine.serialize(current)); const replayed = replayUno(engine, { gameType: "UNO", gameVersion: "1.0.0", initialState: state(), actions: actions.map((action, sequence) => ({ sequence, action, timestamp: new Date(0).toISOString() })) }); expect(restored).toEqual(current); expect(replayed).toEqual(current); });
  it("uses injected random values for deterministic shuffles", () => { expect(new UnoEngine(new MockRandomProvider([0])).createInitialState(config)).toEqual(new UnoEngine(new MockRandomProvider([0])).createInitialState(config)); });
  it("generates only legal actions and rejects malformed serialized state", () => { const { engine } = game(); const current = state(); expect(engine.getValidActions(current, "p1").some((action) => action.type === "DRAW_CARD")).toBe(true); expect(engine.getValidActions(current, "p2")).toEqual([]); expect(() => engine.deserialize("{}")) .toThrow("Invalid UNO state"); });
});
