import { expect, test } from "@playwright/test";

test("two isolated clients use recipient projections, idempotency, stale recovery, and reconnect", async ({ browser }) => {
  const contextA = await browser.newContext({ baseURL: "http://localhost:3100" }); const contextB = await browser.newContext({ baseURL: "http://localhost:3100" });
  const pageA = await contextA.newPage(); const pageB = await contextB.newPage(); const endpoint = "http://localhost:3100/api/dev/realtime";
  const post = async (page: typeof pageA, body: unknown) => { const response = await page.request.post(endpoint, { data: body }); expect(response.ok()).toBe(true); return response.json(); };
  const alpha = { connectionId: "browser-a", userId: "user-a", playerId: "player-a" }; const beta = { connectionId: "browser-b", userId: "user-b", playerId: "player-b" };
  await post(pageA, { op: "reset" }); let room = await post(pageA, { op: "create", identity: alpha, displayName: "Alpha" }); room = await post(pageB, { op: "join", roomCode: room.roomCode, identity: beta, displayName: "Beta" }); room = await post(pageA, { op: "ready", roomCode: room.roomCode, identity: alpha, ready: true, expectedRoomVersion: room.version }); room = await post(pageB, { op: "ready", roomCode: room.roomCode, identity: beta, ready: true, expectedRoomVersion: room.version }); const started = await post(pageA, { op: "start", roomCode: room.roomCode, identity: alpha, expectedRoomVersion: room.version }); const sessionId = started.room.gameSessionId; const snapshotA = await post(pageA, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: alpha.playerId } }); const snapshotB = await post(pageB, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: beta.playerId } });
  expect(snapshotA.projection.ownHand).toHaveLength(1); expect(snapshotB.projection.ownHand).toHaveLength(1); expect(JSON.stringify(snapshotA)).not.toContain(snapshotB.projection.ownHand[0].id);
  const activeIdentity = snapshotA.projection.currentPlayerId === alpha.playerId ? alpha : beta; const activePage = activeIdentity.playerId === alpha.playerId ? pageA : pageB; const activeSnapshot = activeIdentity.playerId === alpha.playerId ? snapshotA : snapshotB; const command = { protocolVersion: 1, requestId: "browser-action-1", gameSessionId: sessionId, playerId: activeIdentity.playerId, expectedStateVersion: activeSnapshot.stateVersion, sentAt: new Date().toISOString(), action: activeSnapshot.projection.legalActions.find((action: { type: string }) => action.type === "DRAW_CARD") };
  const accepted = await post(activePage, { op: "action", identity: activeIdentity, command }); expect(accepted.accepted).toBe(true); expect(await post(activePage, { op: "action", identity: activeIdentity, command })).toEqual(accepted); const afterDuplicate = await post(pageA, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: alpha.playerId } }); expect(afterDuplicate.stateVersion).toBe(accepted.stateVersion);
  const stale = await post(activePage, { op: "action", identity: activeIdentity, command: { ...command, requestId: "browser-stale" } }); expect(stale).toMatchObject({ accepted: false, rejectionCode: "STALE_VERSION", snapshotRequired: true });
  await post(pageB, { op: "disconnect", roomCode: room.roomCode, identity: beta }); const reconnected = await post(pageB, { op: "reconnect", roomCode: room.roomCode, identity: beta }); expect(reconnected.snapshot.stateVersion).toBe(accepted.stateVersion); expect(reconnected.snapshot.lastEventSequence).toBeGreaterThanOrEqual(accepted.events.length);
  const spectator = await post(pageA, { op: "spectate", roomCode: room.roomCode, spectatorId: "spectator" }); expect(spectator.projection.legalActions).toEqual([]); expect(JSON.stringify(spectator)).not.toContain("ownHand");
  const spectatorAction = await post(pageA, { op: "action", identity: { connectionId: "spectator-connection", userId: "spectator-user", playerId: "spectator" }, command: { ...command, requestId: "spectator-action", playerId: "spectator", expectedStateVersion: accepted.stateVersion, action: { ...command.action, playerId: "spectator" } } }); expect(spectatorAction).toMatchObject({ accepted: false, rejectionCode: "UNAUTHORIZED" });
  let finalSnapshot = await post(pageA, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: alpha.playerId } }); for (let step = 0; step < 300 && finalSnapshot.status === "ACTIVE"; step += 1) { const nextIdentity = finalSnapshot.projection.currentPlayerId === alpha.playerId ? alpha : beta; const nextPage = nextIdentity.playerId === alpha.playerId ? pageA : pageB; const playerSnapshot = await post(nextPage, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: nextIdentity.playerId } }); const result = await post(nextPage, { op: "action", identity: nextIdentity, command: { protocolVersion: 1, requestId: `finish-${step}`, gameSessionId: sessionId, playerId: nextIdentity.playerId, expectedStateVersion: playerSnapshot.stateVersion, sentAt: new Date().toISOString(), action: playerSnapshot.projection.legalActions[0] } }); expect(result.accepted).toBe(true); finalSnapshot = await post(pageA, { op: "snapshot", gameSessionId: sessionId, recipient: { type: "PLAYER", playerId: alpha.playerId } }); } expect(finalSnapshot).toMatchObject({ status: "FINISHED", projection: { winnerId: expect.any(String) } });
  await pageA.goto("/dev/realtime"); await expect(pageA.getByRole("heading", { name: "Realtime multiplayer foundation" })).toBeVisible(); await pageA.getByRole("button", { name: "Run mock handoff" }).click(); await expect(pageA.getByRole("status")).toContainText("Mock session");
  await pageA.goto("/games"); await expect(pageA.getByRole("heading", { name: "Find your next table." })).toBeVisible(); await pageA.goto("/dev/realtime"); await expect(pageA.getByRole("heading", { name: "Realtime multiplayer foundation" })).toBeVisible();
  await contextA.close(); await contextB.close();
});
