import { SeededRandomProvider } from "@game-store/game-core";
import { UnoEngine, type UnoAction, type UnoEvent, type UnoGameState } from "@game-store/game-uno";
import { REALTIME_PROTOCOL_VERSION, type ColorClashProjection, type ColorClashPublicEvent, type ColorClashRealtimeEvent, type GameActionCommand, type GameActionResult, type GameSnapshot, type MockIdentity, type MockRoomMember, type MockRoomState, type Recipient } from "./types";

type InternalRoom = MockRoomState;
type InternalSession = { id: string; roomCode: string; engine: UnoEngine; state: UnoGameState; stateVersion: number; sequence: number; status: "ACTIVE" | "FINISHED" | "CLOSED"; events: ColorClashRealtimeEvent[]; idempotency: Map<string, { actionHash: string; result: GameActionResult<ColorClashRealtimeEvent> }> };
const copy = <T>(value: T): T => structuredClone(value);
const now = () => new Date().toISOString();
const safeEvent = (event: UnoEvent): ColorClashPublicEvent => event.type === "CARD_DRAWN" ? { type: event.type, playerId: event.playerId, count: 1 } : event.type === "PENALTY_DRAWN" ? { type: event.type, playerId: event.playerId, count: event.amount } : copy(event);

export class MockColorClashAuthority {
  private readonly rooms = new Map<string, InternalRoom>(); private readonly sessions = new Map<string, InternalSession>(); private readonly userByPlayer = new Map<string, string>(); private roomCounter = 0; private sessionCounter = 0;
  reset() { this.rooms.clear(); this.sessions.clear(); this.userByPlayer.clear(); this.roomCounter = 0; this.sessionCounter = 0; }
  createRoom(identity: MockIdentity, displayName: string) { this.bindIdentity(identity); this.roomCounter += 1; const roomCode = `RT${this.roomCounter.toString().padStart(4, "0")}`; const member: MockRoomMember = { playerId: identity.playerId, displayName: this.safeName(displayName), seat: 0, ready: false, connected: true, isHost: true, control: "HUMAN" }; const room: InternalRoom = { roomId: `room-${this.roomCounter}`, roomCode, gameSlug: "color-clash", status: "WAITING", hostPlayerId: identity.playerId, members: [member], spectators: [], version: 1 }; this.rooms.set(roomCode, room); return copy(room); }
  joinRoom(roomCode: string, identity: MockIdentity, displayName: string) { this.bindIdentity(identity); const room = this.room(roomCode); if (room.status !== "WAITING") throw new Error("ROOM_NOT_JOINABLE"); const existing = room.members.find((member) => member.playerId === identity.playerId); if (existing) { existing.connected = true; return copy(room); } if (room.members.length >= 2) throw new Error("ROOM_FULL"); room.members.push({ playerId: identity.playerId, displayName: this.safeName(displayName), seat: room.members.length, ready: false, connected: true, isHost: false, control: "HUMAN" }); room.version += 1; return copy(room); }
  setReady(roomCode: string, identity: MockIdentity, ready: boolean, expectedRoomVersion: number) { const room = this.room(roomCode); this.assertVersion(room.version, expectedRoomVersion); const member = this.member(room, identity); if (member.control !== "HUMAN") throw new Error("PLAYER_REPLACED"); member.ready = ready; room.version += 1; return copy(room); }
  startGame(roomCode: string, identity: MockIdentity, expectedRoomVersion: number) { const room = this.room(roomCode); this.assertVersion(room.version, expectedRoomVersion); if (room.hostPlayerId !== identity.playerId) throw new Error("UNAUTHORIZED"); if (room.members.length !== 2 || room.members.some((member) => !member.ready || !member.connected)) throw new Error("ROOM_NOT_READY"); if (room.gameSessionId) return { room: copy(room), snapshots: room.members.map((member) => this.snapshot(room.gameSessionId!, { type: "PLAYER", playerId: member.playerId })) }; this.sessionCounter += 1; const id = `game-${this.sessionCounter}`; const engine = new UnoEngine(new SeededRandomProvider(8000 + this.sessionCounter)); const state = engine.createInitialState({ players: room.members.map((member) => ({ id: member.playerId, name: member.displayName, kind: member.control === "BOT" ? "BOT" : "HUMAN" })), cardsPerPlayer: 1 }); const session: InternalSession = { id, roomCode, engine, state, stateVersion: 1, sequence: 0, status: "ACTIVE", events: [], idempotency: new Map() }; this.sessions.set(id, session); room.status = "IN_GAME"; room.gameSessionId = id; room.version += 1; return { room: copy(room), snapshots: room.members.map((member) => this.snapshot(id, { type: "PLAYER", playerId: member.playerId })) }; }
  joinSpectator(roomCode: string, spectatorId: string) { const room = this.room(roomCode); if (!spectatorId.trim()) throw new Error("INVALID_SPECTATOR"); if (!room.spectators.includes(spectatorId)) { if (room.spectators.length >= 8) throw new Error("SPECTATOR_FULL"); room.spectators.push(spectatorId); room.version += 1; } return room.gameSessionId ? this.snapshot(room.gameSessionId, { type: "SPECTATOR" }) : copy(room); }
  submit(identity: MockIdentity, command: GameActionCommand<UnoAction>): GameActionResult<ColorClashRealtimeEvent> { const session = this.session(command.gameSessionId); const key = `${session.id}:${identity.playerId}:${command.requestId}`; const actionHash = JSON.stringify({ playerId: command.playerId, expectedStateVersion: command.expectedStateVersion, action: command.action }); const duplicate = session.idempotency.get(key); if (duplicate) { if (duplicate.actionHash !== actionHash) return this.reject(command, session, "REQUEST_ID_COLLISION", false); return copy(duplicate.result); } const record = (result: GameActionResult<ColorClashRealtimeEvent>) => { if (session.idempotency.size >= 256) session.idempotency.delete(session.idempotency.keys().next().value!); session.idempotency.set(key, { actionHash, result: copy(result) }); return result; }; if (command.protocolVersion !== REALTIME_PROTOCOL_VERSION || !/^[a-z0-9-]{3,128}$/i.test(command.requestId) || !Number.isInteger(command.expectedStateVersion) || Number.isNaN(Date.parse(command.sentAt))) return record(this.reject(command, session, "MALFORMED_COMMAND", false)); const room = this.room(session.roomCode); let member: MockRoomMember; try { member = this.member(room, identity); } catch { return record(this.reject(command, session, "UNAUTHORIZED", false)); } if (command.playerId !== identity.playerId || member.control !== "HUMAN") return record(this.reject(command, session, "UNAUTHORIZED", false)); if (session.status !== "ACTIVE") return record(this.reject(command, session, "SESSION_CLOSED", false)); if (command.expectedStateVersion !== session.stateVersion) return record(this.reject(command, session, "STALE_VERSION", true)); if (command.action.playerId !== identity.playerId) return record(this.reject(command, session, "UNAUTHORIZED", false)); const validation = session.engine.validateAction(session.state, command.action); if (!validation.valid) return record(this.reject(command, session, "INVALID_ACTION", false, validation.message)); const transition = session.engine.reduce(session.state, command.action); session.state = transition.state; session.stateVersion += 1; const committed = transition.events.map((event) => { session.sequence += 1; return { eventId: `${session.id}-event-${session.sequence}`, sequenceNumber: session.sequence, gameSessionId: session.id, stateVersion: session.stateVersion, type: event.type, occurredAt: now(), payload: safeEvent(event) } satisfies ColorClashRealtimeEvent; }); session.events.push(...committed); if (session.events.length > 256) session.events.splice(0, session.events.length - 256); if (session.state.phase === "FINISHED") { session.status = "FINISHED"; room.status = "FINISHED"; room.version += 1; } return record({ protocolVersion: 1, requestId: command.requestId, accepted: true, gameSessionId: session.id, stateVersion: session.stateVersion, events: copy(committed) }); }
  snapshot(gameSessionId: string, recipient: Recipient): GameSnapshot<ColorClashProjection> { const session = this.session(gameSessionId); const room = this.room(session.roomCode); if (recipient.type === "PLAYER" && (!recipient.playerId || !room.members.some((member) => member.playerId === recipient.playerId))) throw new Error("UNAUTHORIZED_RECIPIENT"); const playerId = recipient.type === "PLAYER" ? recipient.playerId : undefined; const topDiscard = session.state.discardPile.at(-1)!; const projection: ColorClashProjection = { gameType: "COLOR_CLASH", phase: session.state.phase, currentColor: session.state.currentColor, currentPlayerId: session.state.players[session.state.currentPlayerIndex]!.id, direction: session.state.direction, turnNumber: session.state.turnNumber, topDiscard: copy(topDiscard), drawPileCount: session.state.drawPile.length, players: session.state.players.map((player) => { const member = room.members.find((candidate) => candidate.playerId === player.id)!; return { playerId: player.id, displayName: player.name, handCount: player.hand.length, connected: member.connected, control: member.control }; }), ownHand: playerId ? copy(session.state.players.find((player) => player.id === playerId)!.hand) : undefined, legalActions: playerId ? copy(session.engine.getValidActions(session.state, playerId)) : [], winnerId: session.state.winnerId }; return { protocolVersion: 1, gameSessionId, stateVersion: session.stateVersion, serverTime: now(), recipient: copy(recipient), projection, currentTurn: session.status === "ACTIVE" ? { playerId: projection.currentPlayerId, startedAt: now() } : undefined, status: session.status, lastEventSequence: session.sequence }; }
  disconnect(roomCode: string, identity: MockIdentity) { const room = this.room(roomCode); const member = this.member(room, identity); member.connected = false; member.ready = false; if (member.isHost) { const next = room.members.find((candidate) => candidate.playerId !== member.playerId && candidate.connected && candidate.control === "HUMAN"); if (next) { member.isHost = false; next.isHost = true; room.hostPlayerId = next.playerId; } } room.version += 1; return copy(room); }
  reconnect(roomCode: string, identity: MockIdentity) { const room = this.room(roomCode); const member = this.member(room, identity); if (member.control !== "HUMAN") throw new Error("PLAYER_REPLACED"); member.connected = true; room.version += 1; return room.gameSessionId ? { room: copy(room), snapshot: this.snapshot(room.gameSessionId, { type: "PLAYER", playerId: identity.playerId }) } : { room: copy(room) }; }
  replaceWithBot(roomCode: string, host: MockIdentity, playerId: string, expectedRoomVersion: number) { const room = this.room(roomCode); this.assertVersion(room.version, expectedRoomVersion); if (room.hostPlayerId !== host.playerId) throw new Error("UNAUTHORIZED"); const member = room.members.find((candidate) => candidate.playerId === playerId); if (!member || member.connected || member.isHost) throw new Error("BOT_REPLACEMENT_NOT_ALLOWED"); member.control = "BOT"; room.version += 1; return copy(room); }
  roomSnapshot(roomCode: string) { return copy(this.room(roomCode)); }
  private reject(command: Pick<GameActionCommand<unknown>, "requestId" | "gameSessionId">, session: InternalSession, code: string, snapshotRequired: boolean, message?: string): GameActionResult<ColorClashRealtimeEvent> { return { protocolVersion: 1, requestId: command.requestId, accepted: false, gameSessionId: command.gameSessionId, stateVersion: session.stateVersion, rejectionCode: code, message: message ?? code, retryable: false, snapshotRequired }; }
  private room(code: string) { const room = this.rooms.get(code); if (!room) throw new Error("ROOM_NOT_FOUND"); return room; }
  private session(id: string) { const session = this.sessions.get(id); if (!session) throw new Error("SESSION_NOT_FOUND"); return session; }
  private member(room: InternalRoom, identity: MockIdentity) { this.assertIdentity(identity); if (this.userByPlayer.get(identity.playerId) !== identity.userId) throw new Error("UNAUTHORIZED"); const member = room.members.find((candidate) => candidate.playerId === identity.playerId); if (!member) throw new Error("UNAUTHORIZED"); return member; }
  private bindIdentity(identity: MockIdentity) { this.assertIdentity(identity); const existing = this.userByPlayer.get(identity.playerId); if (existing && existing !== identity.userId) throw new Error("IDENTITY_CONFLICT"); this.userByPlayer.set(identity.playerId, identity.userId); }
  private assertIdentity(identity: MockIdentity) { if (!identity || typeof identity.connectionId !== "string" || typeof identity.userId !== "string" || typeof identity.playerId !== "string" || !identity.connectionId.trim() || !identity.userId.trim() || !identity.playerId.trim()) throw new Error("INVALID_IDENTITY"); }
  private assertVersion(actual: number, expected: number) { if (actual !== expected) throw new Error("STALE_ROOM_VERSION"); }
  private safeName(value: string) { const name = value.trim().slice(0, 32); if (!name) throw new Error("INVALID_DISPLAY_NAME"); return name; }
}
