import { describe, expect, it } from "vitest";
import { PendingCommandRegistry, RealtimeConnectionMachine, RealtimeEventCursor, RequestIdGenerator, RouteSubscriptionRegistry, type GameActionCommand, type RealtimeDomainEvent } from "..";

const command = (requestId: string, version = 1): GameActionCommand<{ type: "DRAW" }> => ({ protocolVersion: 1, requestId, gameSessionId: "game-1", playerId: "p1", expectedStateVersion: version, sentAt: "2026-08-02T00:00:00.000Z", action: { type: "DRAW" } });
const event = (id: string, sequenceNumber: number): RealtimeDomainEvent<{}> => ({ eventId: id, sequenceNumber, gameSessionId: "game-1", stateVersion: sequenceNumber, type: "TEST", occurredAt: "2026-08-02T00:00:00.000Z", payload: {} });

describe("realtime client foundations", () => {
  it("generates stable unique request IDs", () => { const ids = new RequestIdGenerator("client-a"); expect(ids.next(100)).toBe("client-a-2s-1"); expect(ids.next(100)).toBe("client-a-2s-2"); expect(() => new RequestIdGenerator("!" )).toThrow(); });
  it("bounds, acknowledges, and clears pending commands", () => { const registry = new PendingCommandRegistry<{ type: "DRAW" }>(2); expect(registry.add(command("one"))).toBe(true); expect(registry.add(command("one"))).toBe(false); registry.add(command("two", 2)); expect(() => registry.add(command("three"))).toThrow("limit"); expect(registry.acknowledge({ protocolVersion: 1, requestId: "one", accepted: true, gameSessionId: "game-1", stateVersion: 2 })).toBe(true); expect(registry.acknowledge({ protocolVersion: 1, requestId: "missing", accepted: false, gameSessionId: "game-1", stateVersion: 2 })).toBe(false); registry.clearStale(2); expect(registry.pending()).toHaveLength(0); registry.clearSession("game-1"); expect(registry.size()).toBe(0); });
  it("deduplicates events, detects gaps, and resets from snapshots", () => { const cursor = new RealtimeEventCursor(2); expect(cursor.accept(event("one", 1))).toBe("ACCEPTED"); expect(cursor.accept(event("one", 1))).toBe("DUPLICATE"); expect(cursor.accept(event("old", 1))).toBe("OLD"); expect(cursor.accept(event("gap", 3))).toBe("GAP"); expect(cursor.accept(event("two", 2))).toBe("ACCEPTED"); expect(cursor.accept(event("three", 3))).toBe("ACCEPTED"); expect(cursor.accept(event("one", 1))).toBe("OLD"); cursor.applySnapshot({ protocolVersion: 1, gameSessionId: "game-1", stateVersion: 8, serverTime: "now", recipient: { type: "SPECTATOR" }, projection: {}, status: "ACTIVE", lastEventSequence: 7 }); expect(cursor.currentSequence()).toBe(7); });
  it("enforces connection transitions and retry limits", () => { const machine = new RealtimeConnectionMachine(1); expect(machine.transition("CONNECTING").status).toBe("CONNECTING"); machine.transition("AUTHENTICATING"); machine.transition("CONNECTED", { connectionId: "c1" }); machine.transition("RECONNECTING"); machine.transition("AUTHENTICATING"); machine.transition("DISCONNECTED"); expect(machine.transition("RECONNECTING").status).toBe("FAILED"); expect(() => machine.transition("CONNECTED")).toThrow("Invalid realtime transition"); });
  it("replaces stale listeners and releases every route subscription", () => { const registry = new RouteSubscriptionRegistry(); let released = 0; registry.bind("game:events", () => { released += 1; }); registry.bind("game:events", () => { released += 1; }); expect(released).toBe(1); registry.bind("room:snapshot", () => { released += 1; }); expect(registry.release("missing")).toBe(false); expect(registry.release("room:snapshot")).toBe(true); registry.cleanup(); expect(registry.size()).toBe(0); expect(released).toBe(3); expect(() => registry.bind(" ", () => undefined)).toThrow(); });
});
