import { describe, expect, it } from "vitest";
import { MockColorClashAuthority, type GameActionCommand, type MockIdentity } from "..";
import type { UnoAction } from "@game-store/game-uno";

const a: MockIdentity = { connectionId: "connection-a", userId: "user-a", playerId: "player-a" };
const b: MockIdentity = { connectionId: "connection-b", userId: "user-b", playerId: "player-b" };
const setup = () => { const service = new MockColorClashAuthority(); let room = service.createRoom(a, "Alpha"); room = service.joinRoom(room.roomCode, b, "Beta"); room = service.setReady(room.roomCode, a, true, room.version); room = service.setReady(room.roomCode, b, true, room.version); const started = service.startGame(room.roomCode, a, room.version); return { service, room: started.room, sessionId: started.room.gameSessionId! }; };
const actionCommand = (requestId: string, gameSessionId: string, playerId: string, expectedStateVersion: number, action: UnoAction): GameActionCommand<UnoAction> => ({ protocolVersion: 1, requestId, gameSessionId, playerId, expectedStateVersion, sentAt: "2026-08-02T00:00:00.000Z", action });

describe("mock authoritative Color Clash flow", () => {
  it("creates, joins, readies, starts, and filters player/spectator projections", () => { const { service, room, sessionId } = setup(); const first = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); const second = service.snapshot(sessionId, { type: "PLAYER", playerId: b.playerId }); const spectator = service.joinSpectator(room.roomCode, "spectator-1"); expect(first.projection.ownHand).toHaveLength(1); expect(second.projection.ownHand).toHaveLength(1); expect(JSON.stringify(first)).not.toContain(second.projection.ownHand![0]!.id); expect(spectator).toMatchObject({ recipient: { type: "SPECTATOR" }, projection: { legalActions: [] } }); expect(JSON.stringify(spectator)).not.toContain("ownHand"); });
  it("accepts one versioned action, returns the original duplicate result, and rejects stale/spoofed intent", () => { const { service, sessionId } = setup(); const snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); const active = snapshot.projection.currentPlayerId === a.playerId ? a : b; const activeSnapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: active.playerId }); const action = activeSnapshot.projection.legalActions.find((candidate) => candidate.type === "DRAW_CARD")!; const command = actionCommand("request-1", sessionId, active.playerId, activeSnapshot.stateVersion, action); const accepted = service.submit(active, command); expect(accepted.accepted).toBe(true); expect(service.submit(active, command)).toEqual(accepted); const stale = service.submit(active, actionCommand("request-stale", sessionId, active.playerId, activeSnapshot.stateVersion, action)); expect(stale).toMatchObject({ accepted: false, rejectionCode: "STALE_VERSION", snapshotRequired: true }); const other = active.playerId === a.playerId ? b : a; const spoof = service.submit(other, actionCommand("request-spoof", sessionId, active.playerId, accepted.stateVersion, action)); expect(spoof).toMatchObject({ accepted: false, rejectionCode: "UNAUTHORIZED" }); });
  it("migrates room host, resynchronizes reconnect, and supports bounded bot replacement", () => { const { service, room, sessionId } = setup(); const migrated = service.disconnect(room.roomCode, a); expect(migrated.hostPlayerId).toBe(b.playerId); const reconnected = service.reconnect(room.roomCode, a); expect(reconnected).toMatchObject({ snapshot: { gameSessionId: sessionId, recipient: { playerId: a.playerId } } }); let current = service.disconnect(room.roomCode, a); current = service.replaceWithBot(room.roomCode, b, a.playerId, current.version); expect(current.members.find((member) => member.playerId === a.playerId)?.control).toBe("BOT"); expect(() => service.reconnect(room.roomCode, a)).toThrow("PLAYER_REPLACED"); });
  it("finishes only from authoritative valid actions and confirms the result", () => { const { service, sessionId } = setup(); let sequence = 0; let snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); while (snapshot.status === "ACTIVE" && sequence < 300) { const identity = snapshot.projection.currentPlayerId === a.playerId ? a : b; const playerSnapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: identity.playerId }); const action = playerSnapshot.projection.legalActions[0]!; const result = service.submit(identity, actionCommand(`finish-${sequence}`, sessionId, identity.playerId, playerSnapshot.stateVersion, action)); expect(result.accepted).toBe(true); snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); sequence += 1; } expect(snapshot.status).toBe("FINISHED"); expect(snapshot.projection.winnerId).toBeTruthy(); expect(sequence).toBeLessThan(300); });
  it("never exposes private draw IDs in committed public events", () => { const { service, sessionId } = setup(); let snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); const identity = snapshot.projection.currentPlayerId === a.playerId ? a : b; snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: identity.playerId }); const draw = snapshot.projection.legalActions.find((action) => action.type === "DRAW_CARD")!; const result = service.submit(identity, actionCommand("draw", sessionId, identity.playerId, snapshot.stateVersion, draw)); expect(JSON.stringify(result.events)).not.toContain("cardId"); expect(JSON.stringify(result.events)).not.toContain("cardIds"); });
  it("binds a player seat to the mock user identity and rejects malformed commands", () => { const { service, sessionId } = setup(); const snapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: a.playerId }); const active = snapshot.projection.currentPlayerId === a.playerId ? a : b; const activeSnapshot = service.snapshot(sessionId, { type: "PLAYER", playerId: active.playerId }); const draw = activeSnapshot.projection.legalActions.find((action) => action.type === "DRAW_CARD")!; const impostor = { ...active, userId: "other-user" }; expect(service.submit(impostor, actionCommand("impostor", sessionId, active.playerId, activeSnapshot.stateVersion, draw))).toMatchObject({ accepted: false, rejectionCode: "UNAUTHORIZED" }); expect(service.submit(active, { ...actionCommand("bad", sessionId, active.playerId, activeSnapshot.stateVersion, draw), sentAt: "bad-date" })).toMatchObject({ accepted: false, rejectionCode: "MALFORMED_COMMAND" }); });
});
