"use client";

import { useRef } from "react";
import type { AnimationCommand, AnimationSpeed } from "@game-store/animation-core";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ConnectionTransition, MotionSafe, PageTransition, PresenceTransition } from "@/features/animation/primitives";
import { useAnimationQueue } from "@/features/animation/provider";

export function AnimationPreview() {
  const { queue, state, speed, setSpeed, reducedMotion, override, setOverride, isInputBlocked } = useAnimationQueue();
  const sequence = useRef(0);
  const enqueue = (priority: AnimationCommand["priority"], groupId?: string) => { sequence.current += 1; queue.enqueue({ id: `preview-${sequence.current}`, type: priority === "CRITICAL" ? "DICE_SETTLED" : "CARD_HOVER", sourceEventId: `preview-event-${sequence.current}`, sourceEventSequence: sequence.current, payload: { label: priority }, priority, blocking: priority === "CRITICAL", skippable: priority !== "CRITICAL", durationMs: priority === "DECORATIVE" ? 760 : 220, groupId, createdAt: sequence.current }); };
  return <PageTransition><MotionSafe className="mx-auto max-w-[var(--readable-max)] space-y-5 p-[var(--page-padding)]"><header><p className="font-semibold text-primary">Development-only motion preview</p><h1 className="mt-1 font-display text-3xl font-bold">Animation queue</h1><p className="mt-2 text-muted-foreground">Commands are presentation-only and complete from committed events.</p></header><Card><h2 className="font-bold">Preferences</h2><div className="mt-3 flex flex-wrap gap-2">{(["OFF", "FAST", "NORMAL", "SLOW"] as const).map((value) => <Button key={value} size="compact" variant={speed === value ? "secondary" : "outline"} aria-pressed={speed === value} onClick={() => setSpeed(value as AnimationSpeed)}>{value}</Button>)}</div><div className="mt-3 flex flex-wrap gap-2">{(["SYSTEM", "REDUCED", "FULL"] as const).map((value) => <Button key={value} size="compact" variant={override === value ? "secondary" : "outline"} aria-pressed={override === value} onClick={() => setOverride(value)}>{value}</Button>)}</div><p className="mt-3 text-sm text-muted-foreground">Reduced motion effective: {reducedMotion ? "yes" : "no"}</p></Card><Card><h2 className="font-bold">Queue controls</h2><div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => enqueue("CRITICAL")}>Enqueue critical</Button><Button variant="outline" onClick={() => enqueue("NORMAL", "move")}>Enqueue movement</Button><Button variant="outline" onClick={() => enqueue("DECORATIVE", "move")}>Enqueue decoration</Button><Button variant="outline" onClick={() => queue.skipCurrent()}>Skip</Button><Button variant="outline" onClick={() => queue.fastForward()}>Fast-forward</Button><Button variant="outline" onClick={() => queue.resetForReconnect()}>Simulate reconnect</Button></div><PresenceTransition open={Boolean(state.current)}><p className="mt-4 rounded-control bg-muted p-3 text-sm" role="status">{state.status}: {state.current?.type ?? "No command"}{state.parallel.length ? ` + ${state.parallel.length} parallel` : ""}</p></PresenceTransition><p className="mt-2 text-sm text-muted-foreground">Relevant input blocked: {isInputBlocked ? "yes" : "no"}</p></Card><ConnectionTransition status={state.status === "CANCELLED" ? "RECONNECTING" : "IDLE"} /></MotionSafe></PageTransition>;
}
