import type { AudioCommand } from "@game-store/audio-core";
import type { UnoEvent } from "@game-store/game-uno";
import type { RoyalRaceEvent } from "@game-store/game-royal-race";
import type { PropertyEmpireEvent } from "@game-store/game-property-empire";
import type { MoonVillagePublicProjection } from "@game-store/game-moon-village";

const create = (assetId: AudioCommand["assetId"], category: AudioCommand["category"], sourceEventId: string, sequence: number, caption: string, priority: AudioCommand["priority"] = "NORMAL"): AudioCommand => ({ id: `${sourceEventId}:${assetId}`, assetId, category, sourceEventId, sourceEventSequence: sequence, caption, priority, authorizedAudience: "PUBLIC", createdAt: sequence });
export const adaptColorClashAudio = (event: UnoEvent, sourceEventId: string, sequence: number) => event.type === "CARD_PLAYED" ? [create("color-card-played", "GAMEPLAY", sourceEventId, sequence, "Card played.")] : event.type === "GAME_WON" ? [create("game-result", "SYSTEM", sourceEventId, sequence, "Match complete.", "CRITICAL")] : [];
export const adaptRoyalRaceAudio = (event: RoyalRaceEvent, sourceEventId: string, sequence: number) => event.type === "DICE_ROLLED" ? [create("royal-die-settled", "GAMEPLAY", sourceEventId, sequence, `Die settled on ${event.value}.`)] : event.type === "GAME_FINISHED" ? [create("game-result", "SYSTEM", sourceEventId, sequence, "Match complete.", "CRITICAL")] : [];
export const adaptPropertyEmpireAudio = (event: PropertyEmpireEvent, sourceEventId: string, sequence: number) => event.type === "TOKEN_MOVED" ? [create("property-token-arrived", "GAMEPLAY", sourceEventId, sequence, "Token arrived at its destination.")] : event.type === "EVENT_CARD_DRAWN" ? [create("property-dispatch", "GAMEPLAY", sourceEventId, sequence, "Public dispatch revealed.")] : [];
export const adaptMoonVillagePublicAudio = (projection: MoonVillagePublicProjection) => projection.phase === "DAY_ANNOUNCEMENT" ? [create("moon-public-transition", "GAMEPLAY", `moon-public-${projection.sequence}`, projection.sequence, "Village phase changed.")] : projection.phase === "FINISHED" ? [create("game-result", "SYSTEM", `moon-public-${projection.sequence}`, projection.sequence, "Match complete.", "CRITICAL")] : [];
export type RoomPublicAudioEvent = { type: "PLAYER_READY" | "GAME_STARTING" | "RESYNCED"; sequence: number };
export const adaptRoomPublicAudio = (event: RoomPublicAudioEvent) => [create(event.type === "PLAYER_READY" ? "room-ready" : event.type === "GAME_STARTING" ? "room-start" : "system-resynced", event.type === "RESYNCED" ? "SYSTEM" : "ROOM", `room-public-${event.sequence}`, event.sequence, event.type === "PLAYER_READY" ? "Player ready." : event.type === "GAME_STARTING" ? "Game starting." : "Resynchronized to the latest room state.", event.type === "RESYNCED" ? "CRITICAL" : "NORMAL")];
