"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function RealtimePreview() {
  const [status, setStatus] = useState("Idle. No transport is connected."); const [busy, setBusy] = useState(false);
  const demonstrate = async () => { setBusy(true); try { const post = async (body: unknown) => { const response = await fetch("/api/dev/realtime", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); return value; }; const alpha = { connectionId: "preview-a", userId: "preview-user-a", playerId: "preview-player-a" }; const beta = { connectionId: "preview-b", userId: "preview-user-b", playerId: "preview-player-b" }; await post({ op: "reset" }); let room = await post({ op: "create", identity: alpha, displayName: "Alpha" }); room = await post({ op: "join", roomCode: room.roomCode, identity: beta, displayName: "Beta" }); room = await post({ op: "ready", roomCode: room.roomCode, identity: alpha, ready: true, expectedRoomVersion: room.version }); room = await post({ op: "ready", roomCode: room.roomCode, identity: beta, ready: true, expectedRoomVersion: room.version }); const started = await post({ op: "start", roomCode: room.roomCode, identity: alpha, expectedRoomVersion: room.version }); const first = started.snapshots[0]; const second = started.snapshots[1]; setStatus(`Mock session ${started.room.gameSessionId} created. Alpha sees ${first.projection.ownHand.length} private card; Beta sees ${second.projection.ownHand.length}. Opponent hands remain counts only.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Mock flow failed."); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-[var(--readable-max)] space-y-5 p-[var(--page-padding)]"><header><p className="font-semibold text-primary">Development-only authority diagnostics</p><h1 className="mt-1 font-display text-3xl font-bold">Realtime multiplayer foundation</h1><p className="mt-2 text-muted-foreground">In-memory HTTP diagnostics for protocol and projection testing. This is not Socket.IO, authentication, persistence, matchmaking, or production realtime.</p></header><Card><h2 className="text-xl font-bold">Controlled Color Clash handoff</h2><p className="mt-2 text-sm text-muted-foreground">Creates two mock identities, versioned room membership, ready acknowledgements, one authoritative game session, and separate recipient projections.</p><Button className="mt-4" loading={busy} onClick={() => void demonstrate()}>Run mock handoff</Button><p className="mt-4 rounded-control bg-muted p-3 text-sm" role="status">{status}</p></Card><Card><h2 className="text-xl font-bold">Authority boundary</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground"><li>Full deck, random state, legal validation, turns, and winner stay in the mock authority.</li><li>Request IDs and expected versions protect every game intent.</li><li>Reconnect returns a fresh projection and never an event backlog.</li><li>Animation/audio integration consumes committed safe event envelopes only.</li></ul></Card></main>;
}
