"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

const navItems = [{ href: "/", label: "Home" }, { href: "/games", label: "Games" }, { href: "/play", label: "Play" }, { href: "/friends", label: "Friends" }, { href: "/profile", label: "Profile" }];
export function AppShell({ children }: { children: React.ReactNode }) { const path = usePathname(); return <div className="min-h-screen bg-background"><a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 rounded-button bg-primary px-4 py-3 text-primary-foreground">Skip to content</a><header className="sticky top-0 z-20 border-b bg-surface-overlay backdrop-blur"><div className="mx-auto flex h-16 max-w-[var(--content-max)] items-center justify-between px-[var(--page-padding)]"><Link href="/" className="font-display text-xl font-bold text-foreground">Game Store</Link><nav aria-label="Primary" className="hidden items-center gap-1 md:flex">{navItems.map((item) => <NavLink key={item.href} item={item} active={path === item.href || (item.href !== "/" && path.startsWith(item.href))} />)}</nav><Badge variant="offline">Guest · offline-ready</Badge></div></header><main id="main-content" className="mx-auto max-w-[var(--content-max)] px-[var(--page-padding)] py-8 pb-24 md:pb-8">{children}</main><nav aria-label="Mobile primary" className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t bg-surface p-1 md:hidden">{navItems.map((item) => <NavLink key={item.href} item={item} active={path === item.href || (item.href !== "/" && path.startsWith(item.href))} />)}</nav></div>; }
function NavLink({ item, active }: { item: { href: string; label: string }; active: boolean }) { return <Link href={item.href} aria-current={active ? "page" : undefined} className={cn("min-h-11 rounded-button px-3 py-2 text-center text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground", active && "bg-primary-subtle text-primary")}>{item.label}</Link>; }
