import { describe, expect, it } from "vitest";
import { MockRandomProvider, SeededRandomProvider } from "@game-store/game-core";
import { FINISH_POSITION, RoyalRaceEngine, type RoyalRaceState } from "../engine";
import { RoyalRaceBot } from "../bot";

const config = { players: [{ id: "p1", name: "One" }, { id: "p2", name: "Two", kind: "BOT" as const }] };
const setup = () => { const engine = new RoyalRaceEngine(new SeededRandomProvider(7)); return { engine, state: engine.createInitialState(config) }; };

describe("RoyalRaceEngine", () => {
  it("rolls deterministically, exposes legal pieces, and deploys only on six", () => { const engine = new RoyalRaceEngine(new MockRandomProvider([0.99])); const rolled = engine.reduce(engine.createInitialState(config), { type: "ROLL_DICE", playerId: "p1" }); expect(rolled.state.dice).toBe(6); expect(engine.getLegalPieceIds(rolled.state, "p1")).toHaveLength(4); const moved = engine.reduce(rolled.state, { type: "MOVE_PIECE", playerId: "p1", pieceId: "p1-1" }); expect(moved.state.pieces.find((piece) => piece.id === "p1-1")?.position).toBe(0); expect(moved.events.some((event) => event.type === "EXTRA_TURN_GRANTED")).toBe(true); });
  it("auto-passes when no home piece can use the roll", () => { const engine = new RoyalRaceEngine(new MockRandomProvider([0])); const result = engine.reduce(engine.createInitialState(config), { type: "ROLL_DICE", playerId: "p1" }); expect(result.state.currentPlayerIndex).toBe(1); expect(result.events.some((event) => event.type === "NO_LEGAL_MOVE")).toBe(true); });
  it("captures on an unsafe shared cell", () => { const { engine, state } = setup(); const custom: RoyalRaceState = { ...state, phase: "MOVE", dice: 1, pieces: state.pieces.map((piece) => piece.id === "p1-1" ? { ...piece, position: 0 } : piece.id === "p2-1" ? { ...piece, position: 19 } : piece) }; const result = engine.reduce(custom, { type: "MOVE_PIECE", playerId: "p1", pieceId: "p1-1" }); expect(result.state.pieces.find((piece) => piece.id === "p2-1")?.position).toBe(-1); expect(result.events.some((event) => event.type === "PIECE_CAPTURED")).toBe(true); });
  it("protects safe cells and requires an exact home roll", () => { const { engine, state } = setup(); const safe: RoyalRaceState = { ...state, phase: "MOVE", dice: 1, pieces: state.pieces.map((piece) => piece.id === "p1-1" ? { ...piece, position: 5 } : piece.id === "p2-1" ? { ...piece, position: 0 } : piece) }; const safeResult = engine.reduce(safe, { type: "MOVE_PIECE", playerId: "p1", pieceId: "p1-1" }); expect(safeResult.state.pieces.find((piece) => piece.id === "p2-1")?.position).toBe(0); const nearFinish: RoyalRaceState = { ...state, phase: "MOVE", dice: 2, pieces: state.pieces.map((piece) => piece.id === "p1-1" ? { ...piece, position: FINISH_POSITION - 1 } : piece) }; expect(engine.validateAction(nearFinish, { type: "MOVE_PIECE", playerId: "p1", pieceId: "p1-1" })).toMatchObject({ valid: false, code: "ILLEGAL_MOVE" }); });
  it("serializes safely and bots submit legal actions", () => { const { engine, state } = setup(); expect(engine.deserialize(engine.serialize(state))).toEqual(state); expect(() => engine.deserialize("{}")) .toThrow(); const action = new RoyalRaceBot(engine, new SeededRandomProvider(1)).chooseAction(state, "p1"); expect(engine.validateAction(state, action)).toEqual({ valid: true }); });
});
